name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-platform-build:
    name: Cross-Platform Build Check
    runs-on: macos-15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      
      - name: Cache iOS Platform
        uses: actions/cache@v4
        with:
          path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
          key: ios-platform-${{ runner.os }}-xcode-${{ hashFiles('/Applications/Xcode.app/Contents/version.plist') }}
          restore-keys: |
            ios-platform-${{ runner.os }}-xcode-
      
      - name: Build for macOS
        run: |
          echo "Building for macOS..."
          swift build --product FluidAudio
      
      - name: Clean build artifacts
        run: rm -rf .build .swiftpm
      
      - name: Setup iOS Platform
        run: |
          echo "Ensuring iOS platform is installed..."
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -downloadPlatform iOS || echo "iOS platform download failed, may already be installed"
          
          echo "Available SDKs:"
          xcodebuild -showsdks
          
          echo "Available iOS simulators:"
          xcrun simctl list devices available | grep iPhone
      
      - name: Build for iOS
        run: |
          echo "Building for iOS..."
          
          # Show available destinations
          echo "Available destinations:"
          xcodebuild -scheme FluidAudio -showdestinations
          
          # Try building with iPhone 16 Pro and iOS 18.1 (known to be available on macOS 15)
          echo "Building with iPhone 16 Pro (iOS 18.1)..."
          xcodebuild -scheme FluidAudio \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' \
            -derivedDataPath .build/ios \
            build CODE_SIGNING_ALLOWED=NO

  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

